apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: forfeit15-auth
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: forfeit15-auth
  type: LoadBalancer